/**
 * Sound types for keystroke feedback. Each value maps to a synthesized
 * sound generated by Web Audio API (no audio files shipped).
 */
export type SoundType = 'off' | 'click' | 'mech' | 'pop';

export const SOUND_TYPES: SoundType[] = ['off', 'click', 'mech', 'pop'];

export const DEFAULT_SOUND: SoundType = 'off';

export function soundLabel(type: SoundType): string {
  return type;
}
